import Head from 'next/head'
import Navbar from '../components/Navbar'
import TodoForm from '../components/TodoForm'
import dynamic from 'next/dynamic'

export default function Home () {
  const TodoList = dynamic(() => import('../components/TodoList'), {
    ssr: false
  })
  return (
    <div>
      <Head>
        <title>Todo app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='grid place-items-center bg-gray-200 h-screen px-6 font-sans'>
        <Navbar />
        <div className='w-full max-w-3xl shadow-lg rounded-lg p-6 bg-white'>
          <TodoForm />

          <TodoList />
        </div>
      </main>
    </div>
  )
}
